CREATE TABLE PESSOA (
  CPF VARCHAR(12) NOT NULL,
  NOME VARCHAR(250) NOT NULL,
  IDADE NUMBER NOT NULL,
  GENERO VARCHAR(1) NOT NULL,
  TELEFONE NUMBER NOT NULL,
  EMAIL VARCHAR(250) NOT NULL,
  SENHA VARCHAR(250) NOT NULL,
  PROFISSAO VARCHAR(250) NOT NULL,
  CIDADE VARCHAR(250) NOT NULL,
  CONSTRAINT PESSOA_PK PRIMARY KEY (CPF) ENABLE);